name: Stockfish
on:
  push:
    tags:
      - "*"
    branches:
      - master
      - tools
      - github_ci
      - debug_riscv
  pull_request:
    branches:
      - master
      - tools
jobs:
  Tests:
    uses: ./.github/workflows/tests.yml
